; installer/nxlibrarian.nsi - NSIS installer for NX-Librarian (Windows)
;
; Build:
;   makensis installer\nxlibrarian.nsi
;
; Produces:
;   installer\NX-Librarian-Setup.exe
;
; Requires: NSIS 3.x (https://nsis.sourceforge.io)

Unicode True

!define APP_NAME      "NX-Librarian"
!define APP_VERSION   "3.0.0-beta.27"
!define APP_EXE       "NX-Librarian.exe"

Name "${APP_NAME} ${APP_VERSION}"
OutFile "NX-Librarian-Setup.exe"
BrandingText "${APP_NAME} ${APP_VERSION}"
SetCompressor /SOLID lzma

; Portable-only: installs to user-writable AppData — no admin rights needed.
RequestExecutionLevel user
InstallDir "$LOCALAPPDATA\NX-Librarian"

; ---------------------------------------------------------------------------
; MUI
; ---------------------------------------------------------------------------
!include "MUI2.nsh"
!include "LogicLib.nsh"
!include "nsDialogs.nsh"

!define MUI_ABORTWARNING
!define MUI_ICON "..\icon.ico"
!define MUI_UNICON "..\icon.ico"

; Finish page — offer to launch the app
!define MUI_FINISHPAGE_RUN "$INSTDIR\${APP_EXE}"

; Pages
Page custom ShortcutPageCreate ShortcutPageLeave
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_LANGUAGE "English"

; ---------------------------------------------------------------------------
; Desktop shortcut option
; ---------------------------------------------------------------------------
Var Dialog
Var CheckDesktop
Var DesktopShortcut

Function ShortcutPageCreate
    ; Custom pages are NOT auto-skipped by /S — must check explicitly.
    ${If} ${Silent}
        Abort
    ${EndIf}

    nsDialogs::Create 1018
    Pop $Dialog
    ${If} $Dialog == error
        Abort
    ${EndIf}

    ${NSD_CreateLabel} 0 0 100% 20u \
        "Choose install location on the next page (default: AppData\Local\NX-Librarian)."

    ${NSD_CreateCheckbox} 10u 30u 90% 14u "Create Desktop shortcut"
    Pop $CheckDesktop
    ${NSD_SetState} $CheckDesktop ${BST_CHECKED}

    nsDialogs::Show
FunctionEnd

Function ShortcutPageLeave
    ${NSD_GetState} $CheckDesktop $DesktopShortcut
FunctionEnd

; ---------------------------------------------------------------------------
; Installer
; ---------------------------------------------------------------------------
Section "Main Application" SecMain
    SectionIn RO

    ; Close any running instance so the exe is not locked during install.
    ; Silent for both auto-update (process already dead) and manual installs.
    nsExec::Exec 'taskkill /F /IM "${APP_EXE}" /T'
    Sleep 1500

    ; Install the full onedir bundle.
    ; filelist.nsh is generated by build_scripts/gen_nsis_filelist.py
    ; (or the equivalent CI step) before makensis is called.
    ; It contains SetOutPath + File lines for every file in dist\NX-Librarian\.
    !include "filelist.nsh"

    ; Auto-update (silent): files are replaced, batch script relaunches.
    ${If} ${Silent}
        Return
    ${EndIf}

    ; Desktop shortcut (optional)
    ${If} $DesktopShortcut == ${BST_CHECKED}
        CreateShortcut "$DESKTOP\NX-Librarian.lnk" "$INSTDIR\${APP_EXE}"
    ${EndIf}
SectionEnd

